a="Hazbi 22"
x=a.isalnum()
print(x)
x=a.isalpha()
print(x)
x=a.isdigit()
print(x)
x=a.islower()
print(x)
x=a.isupper()
print(x)
x=a.swapcase()
print(x)
x=a.isnumeric()
print(x)
x=a.istitle()
print(x)
x=a.isspace()
print(x)
list1=[11 , 22, 26]
x=list1.count(11)
print(x)
list1.sort()
print('Sorted list:', list1)
list2=['apple', 'orange', 'grapes']
x=list2.reverse()
print('Reversed list:', list2)
min(list1)
print('Minimum of list:', min(list1))
min(list2)
print('Minimum:', min(list2))
max(list1)
print('Maximum:', max(list1))
max(list2)
print('Maximum:', max(list2))

